# -*- coding: utf-8 -*-
"""Argus_Pro_v3_Saglik_Paneli.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/xxxxxxxxxx
"""

# Colab için gerekli kurulumlar ve bağımlılıklar
!pip install streamlit plotly pandas requests streamlit-option-menu colab-xterm

# Colab-xterm'i yükle ve aktifleştir
!pip install colab-xterm
from google.colab import output
output.enable_custom_widget_manager()

import threading
import time
import requests
import pandas as pd
import plotly.graph_objects as go
import streamlit as st
from streamlit_option_menu import option_menu
import base64
from datetime import datetime, timedelta
import os

# Colab'da Streamlit çalıştırmak için localtunnel kurulumu
!npm install -g localtunnel

# Streamlit uygulama kodumuz
streamlit_code = """
import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import requests
from datetime import datetime, timedelta
import time

# Sayfa yapılandırması
st.set_page_config(
    page_title="Argus Pro v3 - Sağlık Paneli",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# FontAwesome ikonları için CSS
st.markdown("""
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
    .stApp {{
        background-color: #0e1117;
    }}
    .card {{
        background: linear-gradient(145deg, #1a1a2e 0%, #16213e 100%);
        border-radius: 20px;
        padding: 1.5rem;
        border-left: 5px solid #8A2BE2;
        box-shadow: 0 10px 30px rgba(138, 43, 226, 0.2);
        transition: transform 0.3s ease;
        color: white;
        margin: 10px 0;
    }}
    .card:hover {{
        transform: translateY(-5px);
        box-shadow: 0 15px 40px rgba(138, 43, 226, 0.3);
    }}
    .metric-value {{
        font-size: 2.5rem;
        font-weight: bold;
        color: #8A2BE2;
        margin: 10px 0;
    }}
    .metric-label {{
        font-size: 1rem;
        color: #b0b0b0;
        text-transform: uppercase;
        letter-spacing: 1px;
    }}
    .progress-bar {{
        width: 100%;
        height: 20px;
        background: #1a1a2e;
        border-radius: 10px;
        margin: 10px 0;
        overflow: hidden;
    }}
    .progress-fill {{
        height: 100%;
        background: linear-gradient(90deg, #8A2BE2, #b066fe);
        border-radius: 10px;
        transition: width 0.5s ease;
    }}
    .water-text {{
        font-size: 1.2rem;
        color: #8A2BE2;
        text-align: center;
    }}
    </style>
    """, unsafe_allow_html=True)

# Session state başlatma
if 'water_intake' not in st.session_state:
    st.session_state.water_intake = 0
if 'access_token' not in st.session_state:
    st.session_state.access_token = ''
if 'activities_data' not in st.session_state:
    st.session_state.activities_data = None
if 'last_fetch' not in st.session_state:
    st.session_state.last_fetch = None

# Başlık
st.markdown("""
    <div style='text-align: center; padding: 2rem;'>
        <i class='fas fa-heartbeat' style='font-size: 4rem; color: #8A2BE2;'></i>
        <h1 style='color: white; font-size: 3rem; margin: 1rem 0;'>Argus Pro <span style='color: #8A2BE2;'>v3</span></h1>
        <p style='color: #b0b0b0;'>Gelişmiş Sağlık Takip Paneli</p>
    </div>
""", unsafe_allow_html=True)

# Sidebar
with st.sidebar:
    st.markdown("<h2 style='color: #8A2BE2; text-align: center;'>⚙️ Kontrol Paneli</h2>", unsafe_allow_html=True)
    
    # Strava Access Token girişi
    st.markdown("### 🔑 Strava Erişim")
    token = st.text_input("Access Token", type="password", key="token_input",
                         help="Strava API Access Token'ınızı girin")
    if token:
        st.session_state.access_token = token
    
    # Su takibi butonu
    st.markdown("### 💧 Su Takibi")
    col1, col2 = st.columns([3, 1])
    with col1:
        if st.button("🚰 +250 ml Su İç", use_container_width=True):
            st.session_state.water_intake = min(st.session_state.water_intake + 250, 3000)
            st.rerun()
    with col2:
        if st.button("🔄 Sıfırla"):
            st.session_state.water_intake = 0
            st.rerun()
    
    # Su ilerleme çubuğu
    water_percentage = (st.session_state.water_intake / 3000) * 100
    st.markdown(f"""
        <div class='water-text'>
            <i class='fas fa-droplet'></i> Günlük Hedef: {st.session_state.water_intake}ml / 3000ml
        </div>
        <div class='progress-bar'>
            <div class='progress-fill' style='width: {water_percentage}%;'></div>
        </div>
        <p style='text-align: center; color: white;'>{water_percentage:.1f}%</p>
    """, unsafe_allow_html=True)
    
    # Veri yenileme butonu
    if st.button("🔄 Verileri Yenile", use_container_width=True):
        st.session_state.last_fetch = None
        st.rerun()

# Ana içerik
def fetch_strava_activities(token):
    \"\"\"Strava'dan aktivite verilerini çeker\"\"\"
    if not token:
        return None
    
    url = "https://www.strava.com/api/v3/athlete/activities"
    headers = {"Authorization": f"Bearer {token}"}
    params = {"per_page": 10, "page": 1}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            return response.json()
        else:
            st.error(f"Strava API Hatası: {response.status_code}")
            return None
    except Exception as e:
        st.error(f"Bağlantı Hatası: {str(e)}")
        return None

# Verileri çek
if st.session_state.access_token and (st.session_state.last_fetch is None or 
                                     (datetime.now() - st.session_state.last_fetch).seconds > 300):
    with st.spinner("Strava verileri yükleniyor..."):
        activities = fetch_strava_activities(st.session_state.access_token)
        if activities:
            st.session_state.activities_data = activities
            st.session_state.last_fetch = datetime.now()

# Metrik kartları
if st.session_state.activities_data:
    activities = st.session_state.activities_data
    
    # Son 10 aktivitenin metriklerini hesapla
    total_distance = sum(act.get('distance', 0) for act in activities) / 1000  # km
    avg_heartrate = 0
    heartrate_count = 0
    total_calories = sum(act.get('calories', 0) for act in activities)
    
    for act in activities:
        if act.get('average_heartrate'):
            avg_heartrate += act['average_heartrate']
            heartrate_count += 1
    
    avg_heartrate = avg_heartrate / heartrate_count if heartrate_count > 0 else 0
    
    # Metrik kartları
    col1, col2, col3 = st.columns(3)
    
    with col1:
        st.markdown(f"""
            <div class='card'>
                <i class='fas fa-route' style='font-size: 2rem; color: #8A2BE2;'></i>
                <div class='metric-label'>Toplam Mesafe</div>
                <div class='metric-value'>{total_distance:.1f} km</div>
                <div style='color: #b0b0b0;'>son 10 aktivite</div>
            </div>
        """, unsafe_allow_html=True)
    
    with col2:
        st.markdown(f"""
            <div class='card'>
                <i class='fas fa-heart' style='font-size: 2rem; color: #8A2BE2;'></i>
                <div class='metric-label'>Ortalama Nabız</div>
                <div class='metric-value'>{avg_heartrate:.0f} bpm</div>
                <div style='color: #b0b0b0;'>son 10 aktivite</div>
            </div>
        """, unsafe_allow_html=True)
    
    with col3:
        st.markdown(f"""
            <div class='card'>
                <i class='fas fa-fire' style='font-size: 2rem; color: #8A2BE2;'></i>
                <div class='metric-label'>Toplam Kalori</div>
                <div class='metric-value'>{total_calories:.0f} kcal</div>
                <div style='color: #b0b0b0;'>son 10 aktivite</div>
            </div>
        """, unsafe_allow_html=True)
    
    # Grafik
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown("<h3 style='color: white;'>📊 Son Aktiviteler - Mesafe Grafiği</h3>", unsafe_allow_html=True)
    
    # Grafik için veri hazırlama
    df = pd.DataFrame([
        {
            'tarih': datetime.fromiso64(act['start_date'].replace('Z', '+00:00')).strftime('%d/%m'),
            'mesafe': act.get('distance', 0) / 1000,  # km
            'isim': act.get('name', 'Aktivite')[:20]
        }
        for act in activities[:10]
    ])
    
    if not df.empty:
        fig = go.Figure()
        fig.add_trace(go.Scatter(
            x=df['tarih'],
            y=df['mesafe'],
            mode='lines+markers',
            name='Mesafe',
            line=dict(color='#8A2BE2', width=3),
            fill='tozeroy',
            fillcolor='rgba(138, 43, 226, 0.2)',
            marker=dict(size=10, color='#8A2BE2', line=dict(color='white', width=2))
        ))
        
        fig.update_layout(
            plot_bgcolor='#0e1117',
            paper_bgcolor='#0e1117',
            font=dict(color='white'),
            xaxis=dict(gridcolor='#333333', title='Tarih'),
            yaxis=dict(gridcolor='#333333', title='Mesafe (km)'),
            hovermode='x unified',
            showlegend=False,
            height=400
        )
        
        st.plotly_chart(fig, use_container_width=True)
        
        # Aktivite tablosu
        st.markdown("<br><h3 style='color: white;'>📋 Son Aktiviteler</h3>", unsafe_allow_html=True)
        df_display = df.copy()
        df_display['mesafe'] = df_display['mesafe'].round(2)
        st.dataframe(
            df_display,
            use_container_width=True,
            hide_index=True,
            column_config={
                "tarih": "Tarih",
                "mesafe": "Mesafe (km)",
                "isim": "Aktivite Adı"
            }
        )
    else:
        st.info("Grafik gösterimi için yeterli veri yok.")
else:
    # Token girilmemişse bilgi mesajı
    st.info("👈 Lütfen sol panelden Strava Access Token'ınızı girin.")
    
    # Örnek kart gösterimi
    col1, col2, col3 = st.columns(3)
    with col1:
        st.markdown("""
            <div class='card' style='opacity: 0.7;'>
                <i class='fas fa-route' style='font-size: 2rem; color: #8A2BE2;'></i>
                <div class='metric-label'>Toplam Mesafe</div>
                <div class='metric-value'>-- km</div>
                <div style='color: #b0b0b0;'>Token girilmedi</div>
            </div>
        """, unsafe_allow_html=True)
    
    with col2:
        st.markdown("""
            <div class='card' style='opacity: 0.7;'>
                <i class='fas fa-heart' style='font-size: 2rem; color: #8A2BE2;'></i>
                <div class='metric-label'>Ortalama Nabız</div>
                <div class='metric-value'>-- bpm</div>
                <div style='color: #b0b0b0;'>Token girilmedi</div>
            </div>
        """, unsafe_allow_html=True)
    
    with col3:
        st.markdown("""
            <div class='card' style='opacity: 0.7;'>
                <i class='fas fa-fire' style='font-size: 2rem; color: #8A2BE2;'></i>
                <div class='metric-label'>Toplam Kalori</div>
                <div class='metric-value'>-- kcal</div>
                <div style='color: #b0b0b0;'>Token girilmedi</div>
            </div>
        """, unsafe_allow_html=True)

# Footer
st.markdown("""
    <div style='text-align: center; padding: 2rem; color: #b0b0b0;'>
        <hr style='border-color: #8A2BE2;'>
        <p>Argus Pro v3 - Gelişmiş Sağlık Takip Paneli</p>
        <p style='font-size: 0.8rem;'>Veriler Strava API üzerinden alınmaktadır</p>
    </div>
""", unsafe_allow_html=True)
"""

# Streamlit uygulamasını bir dosyaya yaz
with open('argus_pro_v3.py', 'w') as f:
    f.write(streamlit_code)

# Colab'da Streamlit'i arka planda çalıştır
def run_streamlit():
    os.system('streamlit run argus_pro_v3.py --server.port 8501 &')

thread = threading.Thread(target=run_streamlit)
thread.start()

# Localtunnel ile public URL oluştur
print("\n" + "="*50)
print("🚀 Argus Pro v3 Sağlık Paneli başlatılıyor...")
print("="*50)
print("\n📡 Public URL oluşturuluyor...\n")

# Localtunnel'ı başlat
!npx localtunnel --port 8501 &

time.sleep(5)

print("\n" + "="*50)
print("✅ Argus Pro v3 hazır!")
print("="*50)
print("\n🔗 Yukarıdaki URL'yi tarayıcınızda açın")
print("⚠️  Not: İlk bağlantıda 'Your connection is not private' uyarısı çıkabilir,")
print("   'Proceed to site' veya 'Visit Site' butonuna tıklayarak devam edin.\n")
print("📝 Kullanım Talimatları:")
print("   1. Strava Access Token'ınızı sol panelden girin")
print("   2. Su takibini butonlarla yapın")
print("   3. Veriler otomatik olarak güncellenecektir\n")
print("="*50)

# Public URL'i göster
!curl -s https://loca.lt/mytunnelpassword | grep -o 'https://[^"]*.loca.lt' || echo "URL alınamadı, yukarıdaki localtunnel çıktısına bakın"
